### ISSUE TITLE
about known issues

### ISSUE THREAD

**Issue by jaruiz-ual** [belucha/oxyplot.blazor#10]
Example code for updating: https://github.com/VisualMelon/oxyplot.blazor/commit/c3241544e070e91ad061f3d8c02642a8a857e7e4

Happy to stuff this into a PR if it helps, but it's only a very rough job.

Known issues:
 - Observed some crashes in some of the newer examples (e.g. AxisExamples, Data Margins, Asymmetric); not worked out why
 - The tracker code used to be formatted on the `PlotModel.Legend*` properties, but those properties no longer exist, so that needs some design work

_Originally posted by @VisualMelon in https://github.com/belucha/oxyplot.blazor/issues/9#issuecomment-1000912401_

**Comment by belucha** [comment]
Sorry for the "delay" ... I think it is fixed by now!
