### ISSUE TITLE
Drawings disappeared in the extra rect when the second svg is higher than the first one

### ISSUE THREAD

**Issue by luanxushen** [belucha/oxyplot.blazor#12]
I met a weird problem when using your project. It is hard for me to fix that and it will be very appreciated if you could help me.
problem as following shown:
![@T_VKHZQ{{TM3~S)I%UROP0](https://github.com/belucha/oxyplot.blazor/assets/26113509/f17f33c9-99aa-447b-873f-49656fb5b6ba)

**Comment by belucha** [comment]
I think this is related to the clip path id that is shared between different svg's within one page.

This is solved by https://github.com/belucha/oxyplot.blazor/commit/89a9fb2d1d32b16a6592d41f3ea1887008bf7e6d

and version 2.5.6

Please close the issues, if it works

and thanks for the feedback
