### ISSUE TITLE
Targeting .NET Core 3.1 (LTS) needs some adjustments

### ISSUE THREAD

**Issue by KaiWall** [belucha/oxyplot.blazor#4]
After cloning, I couldn't get the demo running. I had to set the targetplatform to 3.1 anyway. Thus I had to tinker around a little:
 
OxyPlot.Blazor/BlazorPlotView.cs
   as MouseEventArgs still does not support OffsetX and OffsetY under .NET Core 3.1
      lines 426/435:    Position = new ScreenPoint(e.ClientX - this.ClientArea.Left, e.ClientY - this.ClientArea.Top),
                                //instead of: Position = new ScreenPoint(e.OffsetX, e.OffsetY),

OxyPlot.Blazor/wwwroot/OxyPlot.Blazor.js
   as const r = e.getBoundingClientRect(); still does not contains the property x nor y
     line 10: return [r.left, r.top, r.width, r.height]; 
                 //throws exception: return [r.x ?? 0, r.y ?? 0, r.width ?? 0, r.height ?? 0];
                 //throws exception: return [r.left ?? 0, r.top ?? 0, r.width ?? 0, r.height ?? 0];

 Many thanks to "belucha" to have the wonderful oxyplot around even in the blazor world!

**Comment by belucha** [comment]
net7 supported
